import type { DecisionResult } from '../types/decision'
import type { IdeaMode } from '../types/request'
import { MODE_DESCRIPTORS } from '../types/request'

const VERDICT_LABEL: Record<string, string> = {
  ship: 'SHIP',
  refine: 'REFINE',
  skip: 'SKIP',
}

const LIFT_LABEL: Record<string, string> = {
  small: 'small lift',
  moderate: 'moderate lift',
  large: 'large lift',
}

const SEVERITY_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 }

export function buildEvaluationMarkdown(
  result: DecisionResult,
  idea: string,
  mode: IdeaMode,
): string {
  const modeLabel =
    MODE_DESCRIPTORS.find((d) => d.id === mode)?.label ?? mode

  const lines: string[] = []

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push('# Ship or Skip Evaluation', '')

  // ── Type ────────────────────────────────────────────────────────────────────
  lines.push('## Type', modeLabel, '')

  // ── Input ───────────────────────────────────────────────────────────────────
  lines.push('## Input', '', idea.trim(), '', '---', '')

  // ── Verdict ─────────────────────────────────────────────────────────────────
  lines.push(
    '## Verdict',
    '',
    VERDICT_LABEL[result.verdict] ?? result.verdict.toUpperCase(),
    '',
    `Score: ${result.scorecard.overallScore}/100`,
    `Confidence: ${result.confidence}%`,
    '',
    '---',
    '',
  )

  // ── Executive Summary ────────────────────────────────────────────────────────
  lines.push('## Executive Summary', '', result.summary, '', '---', '')

  // ── Dimension Scores ─────────────────────────────────────────────────────────
  lines.push('## Dimension Scores', '')
  lines.push('| Dimension | Score |')
  lines.push('|-----------|-------|')
  for (const d of result.scorecard.dimensions) {
    lines.push(`| ${d.label} | ${d.score} |`)
  }
  lines.push('', '---', '')

  // ── Risks ────────────────────────────────────────────────────────────────────
  if (result.risks.length > 0) {
    lines.push('## Risks', '')
    const sorted = result.risks
      .slice()
      .sort(
        (a, b) =>
          (SEVERITY_ORDER[a.severity] ?? 99) -
          (SEVERITY_ORDER[b.severity] ?? 99),
      )
    for (const r of sorted) {
      const sev = r.severity.charAt(0).toUpperCase() + r.severity.slice(1)
      lines.push(`### ${sev}`, '', r.statement, '')
    }
    lines.push('---', '')
  }

  // ── Validation Gaps ──────────────────────────────────────────────────────────
  if (result.missingValidation.length > 0) {
    lines.push('## Validation Gaps', '')
    for (const m of result.missingValidation) {
      lines.push(`### ${m.question}`, '')
      lines.push('Reason:', m.whyItMatters, '')
      lines.push('Action:', m.howToCheck, '')
    }
    lines.push('---', '')
  }

  // ── Suggested Direction ──────────────────────────────────────────────────────
  if (result.refineRecommendation) {
    const rec = result.refineRecommendation
    lines.push('## Suggested Direction', '')

    if (rec.whatsWrong.length > 0) {
      lines.push("### What's Wrong", '')
      for (const w of rec.whatsWrong) {
        lines.push(`- ${w}`)
      }
      lines.push('')
    }

    if (rec.improvements.length > 0) {
      lines.push('### Improvements', '')
      for (const imp of rec.improvements) {
        lines.push(`- ${imp.action} _(${LIFT_LABEL[imp.expectedLift] ?? imp.expectedLift})_`)
      }
      lines.push('')
    }

    if (rec.smallerExperiment) {
      lines.push('### Smaller Experiment', '', rec.smallerExperiment, '')
    }

    lines.push('### Re-evaluate When', '', rec.reEvaluateWhen, '')
    lines.push('---', '')
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  lines.push('Generated by Ship or Skip')

  return lines.join('\n')
}
